### ISSUE TITLE
เลือกปัญหาที่เราพบจากบทสัมภาษณ์

### ISSUE THREAD

**Issue by Mmoniyom** [INT100-SEC1-GROUP11/Design-Thinking-Project#6]
-รวมข้อมูลจากแอปต่างๆ  -> 3
-แนะนำงานว่าทำอะไรบ้าง ->4
-ปฎิทินงานหรือกิจกรรม ->4
-ปลุกเข้าเรียน ->3
-แจ้งเตือนเข้างานกับก่อนเดตไลน์ ->6
-เปิดเพลงแล้วก็สามารถดูวีดีโอย้อนหลังได้
-มีพื้นที่ในการเก็บงานหรือจดสรุปงานในหน้าของตนเอง ->2
-สามารถสร้างห้องแชทคุยกันได้ โทรได้
-มีไอคอนสำหรับไมโครซอฟออนไลน์ในการทำงานร่วมกันหรือโปรเเกรมอื่นๆ ->3
เสนอนอกเหนือจากที่มีได้นะ
-----------------------------
คำเสนอเพิ่มเติม
  -สามารถกดตรงปฏิทินดูไฟล์งานที่ได้รับในวันนั้นๆ หรือไฟล์ที่เราจดโน้ตในวันนั้นๆได้
  -ใช้อัลกอริทึ่มในการแก้ปัญหาหรือหาแหล่งอ้างอิงที่เกี่ยวกับงานของเรา

**Comment by Tanapatpusiri** [comment]
บอมสนใจ

- นาฬิกาปลุก
- เเจ้งเตือนเดดไลน์
- มีพื้นที่ในการทำงานร่วมกัน
- เเจ้งเตือนการเข้าเรียน

**Comment by nakatnan** [comment]
เต้ยสนใจ

- แนะนำงานว่าทำอะไรบ้าง
- แจ้งเตือนเข้างานกับก่อนเดตไลน์
- มีพื้นที่ในการเก็บงานหรือจดสรุปงานในหน้าของตนเอง
- ทำงานร่วมกับแอพลิเคชั่นอื่นๆ
- ใช้อัลกอริทึ่มในการแก้ปัญหาหรือหาแหล่งอ้างอิงที่เกี่ยวกับงานของเรา

**Comment by nakatnan** [comment]
เต้ยสนใจ

- แนะนำงานว่าทำอะไรบ้าง
- แจ้งเตือนเข้างานกับก่อนเดตไลน์
- มีพื้นที่ในการเก็บงานหรือจดสรุปงานในหน้าของตนเอง
- ทำงานร่วมกับแอพลิเคชั่นอื่นๆ
- ใช้อัลกอริทึ่มในการแก้ปัญหาหรือหาแหล่งอ้างอิงที่เกี่ยวกับงานของเรา

**Comment by somkarn** [comment]
* สรุปมี *
-รวมข้อมูลจากแอปต่างๆ
-แนะนำงานว่าทำอะไรบ้าง 
-ปฎิทินงานหรือกิจกรรม 
-ปลุกเข้าเรียน 
-แจ้งเตือนเข้างานกับก่อนเดตไลน์
-มีพื้นที่ในการเก็บงานหรือจดสรุปงานในหน้าของตนเอง
-มีไอคอนสำหรับไมโครซอฟออนไลน์ในการทำงานร่วมกันหรือโปรเเกรมอื่นๆ
