### ISSUE TITLE
List Question

### ISSUE THREAD

**Issue by Kasidatep** [INT100-SEC1-GROUP11/Design-Thinking-Project#7]
#### @INT100-SEC1-GROUP11/student 
---

## สรุปคำถามสัมภาษณ์ 
-

**Comment by Mmoniyom** [comment]
ปัญหาที่พบจากในการเรียนออนไลน์

**Comment by Kasidatep** [comment]
ความแตกต่างระหว่างเรียนออนไลน์กับออนไซต์ที่พบมีอะไรบ้าง

**Comment by somkarn** [comment]
ทำงานทันตามเวลาที่กำหนดมั้ย

**Comment by Tanapatpusiri** [comment]
- ตื่นสายบ่อยเเค่ไหน
- จดสิ่งที่เรียนรู้ในวันนั้นไหม
- จดใส่ในไหน
- สะดวกไหม

**Comment by nakatnan** [comment]
-การเรียนออนไลน์ต่างจากการเรียนออนไซต์อย่างไรบ้าง
-ปรับตัวอย่างไรในการเรียนออนไลน์ในระดับมหาวิทยาลัย
-วิชาไหนบ้างที่ไม่สะดวกในการเรียนออนไลน์
-ปัญหาที่พบในการส่งงานที่ได้รับมอบหมาย
-บรรยากาศในการเรียนการสอนเป็นอย่างไรบ้าง

**Comment by Nannapatx** [comment]
- พบปัญหาเกี่ยวกับแอพพลิเคชั่น/โปรแกรม ที่ใช้ทำงานตอนเรียนหรือไม่ ถ้าพบ แก้ปัญหานั้นได้อย่างไร
- พบปัญหาของการแจ้งเตือนการส่งงานหรือไม่ ถ้าพบ แก้ปัญหานั้นได้อย่างไร
- พบปัญหาในการทำงานกลุ่มหรือไม่ ถ้าพบ แก้ปัญหานั้นได้อย่างไร

**Comment by Mmoniyom** [comment]
สรุปคำถาม
-การเรียนออนไลน์ต่างจากการเรียนออนไซต์อย่างไรบ้าง
-เคยพบปัญหาอะไรบ้าง 
-เคยเข้าคลาสสายมั้ย 
-มีปัญการลืมส่งงานหรือการแจ้งเตือนการส่งงานหรือไม่อย่างไร 
-เบื่อเวลาทำงานมั้ย
-เคยประสบปัญหาเวลาทำงานกลุ่มมั้ย 
-มีปัญหากับการเลคเชอร์ในเวลาเรียนมั้ย 
-วิชาไหนบ้างที่ไม่สะดวกในการเรียนออนไลน์
-ปัญหาที่พบในการส่งงานที่ได้รับมอบหมาย
-บรรยากาศในการเรียนการสอนออนไลน์เป็นอย่างไรบ้าง
